src/Web/TechAndTools.Web/Controllers/ContactsController.cs
namespace TechAndTools.Web.Controllers
{
    using Commons.Constants;
    using InputModels.Contacts;
    using Services.Contracts;
    using Services.Mapping;
    using Services.Models;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    
    using System.Threading.Tasks;

    [Authorize(Roles = GlobalConstants.UserRole +", " + GlobalConstants.AdminRole)]
    public class ContactsController : BaseController
    {
        private readonly IContactService contactService;

        public ContactsController(IContactService contactService)
        {
            this.contactService = contactService;
        }

        public IActionResult Contacts()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendContact(CreateContactInputModel inputModel)
        {
            await this.contactService.CreateAsync(inputModel.To<ContactServiceModel>());

            return this.Redirect("/");
        }
    }
}

src/Web/TechAndTools.Web/Controllers/OrdersController.cs
namespace TechAndTools.Web.Controllers
{
    using Commons.Constants;
    using Data.Models;
    using InputModels.Orders;
    using Services.Contracts;
    using Services.Mapping;
    using Services.Models;
    using ViewModels.Addresses;
    using ViewModels.Orders;
    using ViewModels.PaymentMethods;
    using ViewModels.ShoppingCart;
    using ViewModels.Suppliers;
    
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    [Authorize(Roles = GlobalConstants.UserRole + ", " + GlobalConstants.AdminRole)]
    public class OrdersController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;
        private readonly IUserService userService;
        private readonly ISupplierService supplierService;
        private readonly IAddressService addressService;
        private readonly IPaymentMethodService paymentMethodService;
        private readonly IOrderService orderService;

        public OrdersController(IShoppingCartService shoppingCartService,
            IUserService userService,
            ISupplierService supplierService,
            IAddressService addressService,
            IPaymentMethodService paymentMethodService,
            IOrderService orderService)
        {
            this.shoppingCartService = shoppingCartService;
            this.userService = userService;
            this.supplierService = supplierService;
            this.addressService = addressService;
            this.paymentMethodService = paymentMethodService;
            this.orderService = orderService;
        }

        public IActionResult Create()
        {
            if (!this.shoppingCartService.AnyProducts(this.User.Identity.Name))
            {
                return RedirectToAction("Index", "Home");
            }

            TechAndToolsUser user = this.userService
                .GetUserByUsername(this.User.Identity.Name);

            IEnumerable<AddressViewModel> addressesViewModel = this.addressService
                .GetAllByUserId(this.User.FindFirstValue(ClaimTypes.NameIdentifier))
                .To<AddressViewModel>()
                .ToList();

            IEnumerable<SupplierViewModel> supplierViewModels = this.supplierService
                .GetAllSuppliers()
                .To<SupplierViewModel>()
                .ToList();

            IEnumerable<ShoppingCartProductServiceModel> shoppingCartProductsServiceModels = this.shoppingCartService
                .GetAllShoppingCartProducts(this.User.Identity.Name)
                .ToList();

            IEnumerable<PaymentMethodViewModel> paymentMethodViewModels = this.paymentMethodService
                .GetAllPaymentMethods()
                .To<PaymentMethodViewModel>()
                .ToList();

            IEnumerable<ShoppingCartProductViewModel> shoppingCartProductsViewModels = shoppingCartProductsServiceModels
                .Select(x => x.To<ShoppingCartProductViewModel>())
                .ToList();

            CreateOrderInputModel createOrderViewModel = new CreateOrderInputModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                AddressesViewModels = addressesViewModel.ToList(),
                SuppliersViewModel = supplierViewModels,
                ShoppingCartProductViewModels = shoppingCartProductsViewModels,
                PaymentMethodViewModels = paymentMethodViewModels
            };

            return this.View(createOrderViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateOrderInputModel createOrderInputModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Create), createOrderInputModel);
            }

            decimal deliveryPrice = this.supplierService.GetDeliveryPrice(createOrderInputModel.SupplierId, createOrderInputModel.ShippingTo);
            var orderServiceModel = createOrderInputModel.To<OrderServiceModel>();

            var order = await this.orderService.CreateAsync(orderServiceModel, this.User.Identity.Name, deliveryPrice);

            return this.RedirectToAction(nameof(Complete), new { id = order.Id });
        }

        public IActionResult Complete(int id)
        {
            CompleteOrderViewModel viewModel = new CompleteOrderViewModel { OrderId = id };

            return this.View(viewModel);
        }

        public IActionResult Details(int id)
        {
            DetailsOrderViewModel viewModel = this.orderService.GetOrderById(id)
                .To<DetailsOrderViewModel>();

            return this.View(viewModel);
        }

        public IActionResult My()
        {
            string username = this.User.Identity.Name;

            IEnumerable<OrderServiceModel> serviceModels = this.orderService
                .GetAllOrdersByUserId(username)
                .ToList();

            IEnumerable<MyOrdersViewModel> viewModels = serviceModels
                .Select(x => x.To<MyOrdersViewModel>())
                .ToList();

            return this.View(viewModels);
        }
    }
}

src/Web/TechAndTools.Web/Controllers/ProductsController.cs
namespace TechAndTools.Web.Controllers
{
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.Products;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;

        public ProductsController(IProductService productService)
        {
            this.productService = productService;
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var serviceModel = this.productService.GetProductById(id);
            
            ProductDetailsViewModel viewModel = this.productService.GetProductById(id).To<ProductDetailsViewModel>();
            
            return View(viewModel);
        }
    }
}

src/Web/TechAndTools.Web/ViewComponents/CategoriesNavigationViewComponent.cs
namespace TechAndTools.Web.ViewComponents
{
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.MainCategories;
    
    using Microsoft.AspNetCore.Mvc;
    
    using System.Collections.Generic;
    using System.Linq;

    public class CategoriesNavigationViewComponent : ViewComponent
    {
        private readonly IMainCategoryService mainCategoryService;

        public CategoriesNavigationViewComponent(IMainCategoryService mainCategoryService)
        {
            this.mainCategoryService = mainCategoryService;
        }

        public IViewComponentResult Invoke()
        {
            IEnumerable<MainCategoryComponentViewModel> mainCategoriesCategoryComponentViewModels = this.mainCategoryService
                .GetAllMainCategories()
                .To<MainCategoryComponentViewModel>()
                .ToList();
            
            return this.View(mainCategoriesCategoryComponentViewModels);
        }
    }
}

src/Web/TechAndTools.Web/Views/Shared/Partials/_AdminNavbarPartial.cshtml
<nav class="main_nav d-flex flex-row">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="main_nav_content">
                    <div class="main_nav_menu ml-auto">
                        <ul class="standard_dropdown main_nav_dropdown">
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Index"> Към Магазина</a>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Поръчки<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Orders" asp-action="Unprocessed"> Необработени</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Orders" asp-action="Processed"> Обработени</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Orders" asp-action="Delivered"> Доставени</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Запитвания<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Contacts" asp-action="All"> Нови</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Contacts" asp-action="AllArchived"> Архив</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Продукти<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Products" asp-action="Create"> Добави</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Products" asp-action="All"> Всички</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Марки<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Brands" asp-action="Create"> Добави</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Brands" asp-action="All"> Всички</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Категории<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li class="hassubs">
                                        <a href="#"> Главни<i class="fas fa-chevron-right"></i></a>
                                        <ul>
                                            <li>
                                                <a asp-area="Administration" asp-controller="MainCategories" asp-action="Create"> Добави</a>
                                            </li>
                                            <li>
                                                <a asp-area="Administration" asp-controller="MainCategories" asp-action="All"> Всички</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="hassubs">
                                        <a href="#"> Категории<i class="fas fa-chevron-right"></i></a>
                                        <ul>
                                            <li>
                                                <a asp-area="Administration" asp-controller="Categories" asp-action="Create"> Добави</a>
                                            </li>
                                            <li>
                                                <a asp-area="Administration" asp-controller="Categories" asp-action="All"> Всички</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Куриери<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Suppliers" asp-action="Create"> Добави</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Suppliers" asp-action="All"> Всички</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="hassubs">
                                <a href="#"> Статии<i class="fas fa-chevron-down"></i></a>
                                <ul>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Articles" asp-action="Create"> Добави</a>
                                    </li>
                                    <li>
                                        <a asp-area="Administration" asp-controller="Articles" asp-action="All"> Всички</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

src/Web/TechAndTools.Web/Views/Shared/Partials/_FooterPartial.cshtml
        <!-- Footer -->

<footer class="footer">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="footer_col">
                <div class="footer_column footer_contact">
                    <div class="logo_container">
                        <div class="h1 text-primary"><a href="/">TECH&amp;TOOLS</a></div>
                    </div>
                    <div class="footer_social">
                        <ul>
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                            <li><a href="#"><i class="fab fa-google"></i></a></li>
                            <li><a href="#"><i class="fab fa-vimeo-v"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="copyright_container d-flex flex-sm-row flex-column align-items-center justify-content-center">
                    <div class="copyright_content text-center">
                        This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Web/TechAndTools.Web/Views/Shared/Partials/_NavbarPartial.cshtml
<nav class="main_nav">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="main_nav_content d-flex flex-row">

                    @await Component.InvokeAsync("CategoriesNavigation")

                    <div class="main_nav_menu ml-auto">
                        <div class="d-flex justify-content-between">
                            <ul class="standard_dropdown main_nav_dropdown">
                                <li><a href="/"> Магазин<i class="fas fa-chevron-down"></i></a></li>
                                <li><a asp-area="Blog" asp-controller="Articles" asp-action="All"> Блог<i class="fas fa-chevron-down"></i></a></li>
                                <li><a asp-area="" asp-controller="Contacts" asp-action="Contacts"> Контакти<i class="fas fa-chevron-down"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>