src/Web/TechAndTools.Web/Areas/Administration/Controllers/ContactsController.cs
namespace TechAndTools.Web.Areas.Administration.Controllers
{
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.Contacts;

    using Microsoft.AspNetCore.Mvc;

    using System.Linq;
    using System.Threading.Tasks;

    public class ContactsController : AdministrationController
    {
        private readonly IContactService contactService;

        public ContactsController(IContactService contactService)
        {
            this.contactService = contactService;
        }

        public IActionResult All()
        {
            var contacts = this.contactService.GetAllContacts().ToList();
            
            var viewModels = contacts.Select(x => x.To<ContactViewModel>()).ToList();
            
            return View(viewModels);
        }

        public IActionResult AllArchived()
        {
            var contacts = this.contactService
                .GetAllArchivedContacts()
                .ToList();
            
            var viewModels = contacts.Where(x => x.IsArchived == true)
                .Select(x => x.To<ContactViewModel>()).ToList();
            
            return View(viewModels);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.contactService.DeleteAsync(id);

            return RedirectToAction(nameof(AllArchived));
        }

        public IActionResult Archive(int id)
        {
            var userRequests = this.contactService.Archive(id);

            return RedirectToAction(nameof(All));
        }
    }
}

src/Web/TechAndTools.Web/Areas/Administration/Controllers/HomeController.cs
namespace TechAndTools.Web.Areas.Administration.Controllers
{
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.Administration;
    using ViewModels.Orders;

    using Microsoft.AspNetCore.Mvc;
    
    using System.Linq;

    public class HomeController : AdministrationController
    {
        private readonly IOrderService orderService;

        public HomeController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel
            {
                UnprocessedОrdersViewModels = this.orderService.GetUnprocessedOrders()
                    .To<UnprocessedОrderViewModel>()
                    .OrderByDescending(x => x.OrderDate)
                    .ToList(),
                ProcessedОrdersViewModels = this.orderService.GetProcessedOrders()
                    .To<ProcessedОrderViewModel>()
                    .OrderByDescending(x => x.ShippingDate)
                    .ToList()
            };
            
            return View(viewModel);
        }
    }
}

src/Web/TechAndTools.Web/Controllers/ContactsController.cs
namespace TechAndTools.Web.Controllers
{
    using Commons.Constants;
    using InputModels.Contacts;
    using Services.Contracts;
    using Services.Mapping;
    using Services.Models;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    
    using System.Threading.Tasks;

    [Authorize(Roles = GlobalConstants.UserRole +", " + GlobalConstants.AdminRole)]
    public class ContactsController : BaseController
    {
        private readonly IContactService contactService;

        public ContactsController(IContactService contactService)
        {
            this.contactService = contactService;
        }

        public IActionResult Contacts()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendContact(CreateContactInputModel inputModel)
        {
            await this.contactService.CreateAsync(inputModel.To<ContactServiceModel>());

            return this.Redirect("/");
        }
    }
}

src/Web/TechAndTools.Web/Controllers/FavoritesController.cs
namespace TechAndTools.Web.Controllers
{
    using Commons.Constants;
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.Favorites;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using System.Linq;
    using System.Threading.Tasks;

    [Authorize(Roles = TechAndTools.Commons.Constants.GlobalConstants.UserRole +", " + GlobalConstants.AdminRole)]
    public class FavoritesController : BaseController
    {
        private readonly IProductService productService;

        public FavoritesController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult My()
        {
            var favoriteProductsServiceModels = this.productService
                .AllFavoriteProducts(this.User.Identity.Name)
                .ToList();

                var viewModels = favoriteProductsServiceModels
                    .Select(x => x.To<FavoriteProductViewModel>())
                    .ToList();

            return View(viewModels);
        }

        public async Task<IActionResult> AddToFavorites(int id)
        {
            await this.productService.AddToFavoritesAsync(id, this.User.Identity.Name);
            
            return RedirectToAction(nameof(My));
        }

        public async Task<IActionResult> RemoveFromFavorites(int id)
        {
            await this.productService.RemoveFromFavorites(id, this.User.Identity.Name);

            return RedirectToAction(nameof(My));
        }
    }
}

src/Web/TechAndTools.Web/Controllers/HomeController.cs
namespace TechAndTools.Web.Controllers
{
    using Services.Mapping;
    using Services.Contracts;
    using ViewModels;
    using ViewModels.Home;
    using ViewModels.Products;

    using X.PagedList;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;

    [AllowAnonymous]
    public class HomeController : BaseController
    {

        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 15;

        private readonly IProductService productService;

        public HomeController(IProductService productService,
            ICategoryService categoryService)
        {
            this.productService = productService;
        }


        public IActionResult Index(HomeIndexViewModel model)
        {
            IList<ProductIndexViewModel> productIndexViewModels = new List<ProductIndexViewModel>();

            if (model.CategoryId != null)
            {
                productIndexViewModels = this.productService
                    .GetProductsByCategoryId((int)model.CategoryId)
                    .To<ProductIndexViewModel>()
                    .ToList();
            }
            else
            {
                productIndexViewModels = this.productService
                    .GetAllProducts()
                    .To<ProductIndexViewModel>()
                    .ToList();
            }

            int pageNumber = model.PageNumber ?? DefaultPageNumber;
            int pageSize = model.PageSize ?? DefaultPageSize;

            var viewModel = new HomeIndexViewModel
            {
                ProductsViewModels = productIndexViewModels.ToPagedList(pageNumber, pageSize)
            };

            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web/TechAndTools.Web/Controllers/ProductsController.cs
namespace TechAndTools.Web.Controllers
{
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.Products;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;

        public ProductsController(IProductService productService)
        {
            this.productService = productService;
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var serviceModel = this.productService.GetProductById(id);
            
            ProductDetailsViewModel viewModel = this.productService.GetProductById(id).To<ProductDetailsViewModel>();
            
            return View(viewModel);
        }
    }
}

src/Web/TechAndTools.Web/Controllers/ShoppingCartController.cs
namespace TechAndTools.Web.Controllers
{
    using Services.Contracts;
    using Services.Mapping;
    using Services.Models;
    using ViewModels.ShoppingCart;

    using X.PagedList;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    [AllowAnonymous]
    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;


        public ShoppingCartController(IShoppingCartService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        public async Task<IActionResult> MyCart()
        {
            List<ShoppingCartProductServiceModel> shoppingCartProductsServiceModels = await this.shoppingCartService
                .GetAllShoppingCartProducts(this.User.Identity.Name)
                .ToListAsync();

            List<ShoppingCartProductViewModel> shoppingCartProductsViewModels = await shoppingCartProductsServiceModels
                .Select(x => x.To<ShoppingCartProductViewModel>())
                .ToListAsync();

            return this.View(shoppingCartProductsViewModels);

        }

        public async Task<IActionResult> Add(int id, int quantity)
        {
            if (quantity <= 0)
            {
                return this.RedirectToAction(nameof(MyCart));
            }

            await this.shoppingCartService.AddToShoppingCartAsync(id, this.User.Identity.Name, quantity);

            return this.RedirectToAction(nameof(MyCart));
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.shoppingCartService.RemoveProductFromShoppingCart(id, this.User.Identity.Name);

            return this.RedirectToAction(nameof(MyCart));

        }
    }
}

src/Web/TechAndTools.Web/ViewComponents/BrandsFilterViewComponent.cs
namespace TechAndTools.Web.ViewComponents
{
    using Services.Contracts;
    using Services.Mapping;
    using ViewModels.Brands;

    using Microsoft.AspNetCore.Mvc;

    using System.Linq;

    public class BrandsFilterViewComponent : ViewComponent
    {
        private readonly IBrandService brandService;

        public BrandsFilterViewComponent(IBrandService brandService)
        {
            this.brandService = brandService;
        }

        public IViewComponentResult Invoke()
        {
            var brandsViewModels = this.brandService.GetAllBrands().To<BrandListViewModel>().ToList();

            return this.View(brandsViewModels);
        }
    }
}

src/Web/TechAndTools.Web/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Contacts";
}
@section Styles
{
    <link rel="stylesheet" type="text/css" href="~/css/contact_styles.css">
}
<div class="contact_info">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="contact_info_container d-flex flex-lg-row flex-column justify-content-between align-items-between">

                    <!-- Contact Item -->
                    <div class="contact_info_item d-flex flex-row align-items-center justify-content-start">
                        <div class="contact_info_image"><img src="~/images/contact_1.png" alt=""></div>
                        <div class="contact_info_content">
                            <div class="contact_info_title">Phone</div>
                            <div class="contact_info_text">+38 068 005 3570</div>
                        </div>
                    </div>

                    <!-- Contact Item -->
                    <div class="contact_info_item d-flex flex-row align-items-center justify-content-start">
                        <div class="contact_info_image"><img src="~/images/contact_2.png" alt=""></div>
                        <div class="contact_info_content">
                            <div class="contact_info_title">Email</div>
                            <div class="contact_info_text">fastsales@gmail.com</div>
                        </div>
                    </div>

                    <!-- Contact Item -->
                    <div class="contact_info_item d-flex flex-row align-items-center justify-content-start">
                        <div class="contact_info_image"><img src="~/images/contact_3.png" alt=""></div>
                        <div class="contact_info_content">
                            <div class="contact_info_title">Address</div>
                            <div class="contact_info_text">10 Suffolk at Soho, London, UK</div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- Contact Form -->

<div class="contact_form">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="contact_form_container">
                    <div class="contact_form_title">Get in Touch</div>

                    <form action="#" id="contact_form">
                        <div class="contact_form_inputs d-flex flex-md-row flex-column justify-content-between align-items-between">
                            <input type="text" id="contact_form_name" class="contact_form_name input_field" placeholder="Your name" required="required" data-error="Name is required.">
                            <input type="text" id="contact_form_email" class="contact_form_email input_field" placeholder="Your email" required="required" data-error="Email is required.">
                            <input type="text" id="contact_form_phone" class="contact_form_phone input_field" placeholder="Your phone number">
                        </div>
                        <div class="contact_form_text">
                            <textarea id="contact_form_message" class="text_field contact_form_message" name="message" rows="4" placeholder="Message" required="required" data-error="Please, write us a message."></textarea>
                        </div>
                        <div class="contact_form_button">
                            <button type="submit" class="button contact_submit_button">Send Message</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <div class="panel"></div>
</div>

@section Scripts
{
    <script src="~/js/contact_custom.js"></script>
}

src/Web/TechAndTools.Web/Views/Home/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Common
@using X.PagedList.Mvc.Core

@model TechAndTools.Web.ViewModels.Home.HomeIndexViewModel

@{
    ViewData["Title"] = "Home";
}

@section Styles
{
    <link rel="stylesheet" type="text/css" href="~/css/shop_styles.css">
}

<div class="shop">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="shop_sidebar">

                    @await Component.InvokeAsync("CategoriesFilter")

                    @await Component.InvokeAsync("BrandsFilter")

                </div>

            </div>

            <div class="col-lg-9">
                <div class="shop_content">
                    <div class="shop_bar clearfix">
                        <div class="shop_sorting">
                            <span>Sort by:</span>
                            <ul>
                                <li>
                                    <span class="sorting_text">Име<i class="fas fa-chevron-down"></i></span>
                                    <ul>
                                        @*<li class="shop_sorting_button" data-isotope-option='{ "sortBy": "original-order" }'>highest rated</li>*@
                                        <li class="shop_sorting_button" data-isotope-option='{ "sortBy": "name" }'>Име</li>
                                        <li class="shop_sorting_button" data-isotope-option='{ "sortBy": "price" }'>Цена</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="product_grid">
                        <div class="product_grid_border"></div>
                        @foreach (var product in Model.ProductsViewModels)
                        {
                            <div class="product_item is_new">
                                <div class="product_border"></div>
                                <div class="product_image d-flex flex-column align-items-center justify-content-center"><img src="@product.ImageUrl" alt=""></div>
                                <div class="product_content">
                                    <div class="product_price">@product.Price лв.</div>
                                    <div class="product_name"><div><a asp-controller="Products" asp-action="Details" asp-route-id="@product.Id" tabindex="0">@product.Name</a></div></div>
                                </div>
                                @if (product.IsOutOfStock)
                                {
                                    <div class="text-center text-danger">Out Of Stock</div>
                                }
                                else
                                {
                                    <div class="d-flex justify-content-between  mt-1">
                                        <div>
                                            <a class="btn btn-outline-primary mr-1" asp-area="" asp-controller="ShoppingCart" asp-action="Add" asp-route-id="@product.Id" asp-route-quantity="1"><i class="fa fa-cart-plus"></i></a>
                                        </div>
                                        <div>
                                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Favorites" asp-action="AddToFavorites" asp-route-id="@product.Id"><i class="fas fa-heart"></i></a>
                                        </div>
                                    </div>
                                }
                            </div>
                        }

                    </div>
                    <div class="mt-3 d-flex justify-content-around">
                        @Html.PagedListPager((IPagedList)Model.ProductsViewModels, page => Url.Action("Index",
                            new
                                 {
                                PageNumber = page,
                                PageSize = Model.PageSize,
                                     CategoryId = Model.CategoryId,
                                 }),
                            new PagedListRenderOptions
                            {
                                MaximumPageNumbersToDisplay = 5,
                                LiElementClasses = new string[] { "page-item" },
                                PageClasses = new string[] { "page-link" }
                            })
                    </div>

                </div>
            </div>
        </div>
    </div>

    @section Scripts
{
        <script src="~/js/shop_custom.js"></script>
    }